import { SENSITIVE_CATEGORIES } from "./catalog";
import { categoryForNotificationType } from "./event-compat";

export type WhatsAppAudience = "none" | "personal" | "management";

/**
 * Future Meta webhook path (W3+). Do not register a live route until signature
 * verification exists. Do not session-gate-exempt this path until then.
 */
export const FUTURE_WHATSAPP_WEBHOOK_PATH = "/api/internal/whatsapp/webhook";

/**
 * Policy order for WhatsApp channel selection:
 * 1. provider.enabled
 * 2. event allowlisted (audience ≠ none)
 * 3. PAYROLL / sensitive category never WhatsApp
 * 4. personal: category WhatsApp preference AND operational opt-in AND valid E.164
 * 5. management: org management_notification_whatsapp configured (checked at send)
 * Never fallback management → personal phone.
 *
 * Delivery latency (W3, not implemented here): after notify() persists, run a
 * bounded in-process claim/process for that notification_id using the admin
 * client (same SKIP LOCKED path). Cron `0 6 * * *` stays retry/recovery.
 * Do not fire-and-forget an unauthenticated HTTP call.
 */

/** Personal operational WhatsApp — action-required events the app actually emits. */
export const PERSONAL_WHATSAPP_TYPES = new Set([
  "approval.created",
  "approval.required",
  "APPROVAL_ASSIGNED",
  "DOCUMENT_APPROVAL_REQUIRED",
  "APPROVAL_OVERDUE",
  "WORK_ASSIGNED",
]);

/** Org management WhatsApp destination — never a staff personal number. */
export const MANAGEMENT_WHATSAPP_TYPES = new Set([
  "ESCALATION_CREATED",
  "ncr.critical",
  "RISK_HIGH",
  "RISK_CRITICAL",
]);

/**
 * Explicit exclusions (noise, HR-sensitive, or unsafe repeat).
 * PROJECT_OVERDUE is generated by worker scans and can repeat daily; excluded
 * until a dedicated anti-spam/dedup policy exists.
 */
export const NO_WHATSAPP_TYPES = new Set([
  "PROJECT_OVERDUE",
  "PROJECT_DEADLINE_APPROACHING",
  "APPROVAL_REMINDER",
  "MANAGEMENT_DIGEST",
  "attendance.adjusted",
  "attendance.checked_in",
  "attendance.checked_out",
  "payroll.submitted",
  "payroll.reviewed",
  "payroll.approved",
  "payroll.locked",
  "PAYROLL_REVIEW_REQUIRED",
  "PAYROLL_APPROVAL_REQUIRED",
  "PAYROLL_LOCKED_UNPAID",
  "leave_request.submitted",
  "leave_request.approved",
  "leave_request.rejected",
  "leave_request.manager_approved",
  "leave_request.cancelled",
  "LEAVE_SUBMITTED",
  "LEAVE_APPROVED",
  "LEAVE_REJECTED",
  "LEAVE_MANAGER_APPROVED",
  "workflow.mobilization.readiness_changed",
  "workflow.execution.item_updated",
  "workflow.commissioning.item_updated",
  "workflow.handover.item_updated",
]);

export function whatsappAudienceFor(type: string): WhatsAppAudience {
  if (type.startsWith("payroll") || type.startsWith("PAYROLL") || type.startsWith("attendance")) {
    return "none";
  }
  const category = categoryForNotificationType(type);
  if (SENSITIVE_CATEGORIES.has(category)) return "none";
  if (NO_WHATSAPP_TYPES.has(type)) return "none";
  if (MANAGEMENT_WHATSAPP_TYPES.has(type)) return "management";
  if (PERSONAL_WHATSAPP_TYPES.has(type)) return "personal";
  return "none";
}
