/** Presentation-only Arabic labels for audit/event action codes. Raw values stay unchanged. */
const ACTION_LABELS: Record<string, string> = {
  "employee.created": "تم إنشاء موظف",
  "employee.assigned": "تم تعيين موظف",
  "employee.deactivated": "تم إيقاف موظف",
  "employee.employment_updated": "تم تحديث بيانات التوظيف",
  "employee.profile_updated": "تم تحديث ملف الموظف",
  "employee.department_assigned": "تم تعيين إدارة للموظف",
  "job_title.created": "تم إنشاء مسمى وظيفي",
  "job_title.updated": "تم تحديث مسمى وظيفي",
  "job_title.deactivated": "تم تعطيل مسمى وظيفي",
  "job_title.activated": "تم تفعيل مسمى وظيفي",
  "employee.compliance_updated": "تم تحديث الامتثال الوظيفي",
  "employee.login_provisioned": "تم تفعيل دخول موظف",
  "employee_contract.created": "تم إنشاء عقد موظف",
  "employee_document.uploaded": "تم رفع مستند موظف",
  "user.role.changed": "تم تغيير صلاحية مستخدم",
  "role.created": "تم إنشاء دور",
  "role.updated": "تم تحديث دور",
  "role.permissions_changed": "تم تغيير صلاحيات دور",
  "role.deactivated": "تم إيقاف دور",
  "role.reactivated": "تم إعادة تفعيل دور",
  "role.assigned": "تم تعيين دور",
  "role.unassigned": "تم إلغاء تعيين دور",
  "user.deactivated": "تم إيقاف مستخدم",
  "workplace.created": "تم إنشاء موقع عمل",
  "workplace.updated": "تم تحديث موقع عمل",
  "workplace.assigned": "تم تعيين موقع عمل",
  "workplace.assignment_ended": "انتهى تعيين موقع العمل",
  "workplace.assignment_removed": "أُزيل تعيين موقع العمل",
  "attendance.checked_in": "تم تسجيل حضور",
  "attendance.checked_out": "تم تسجيل انصراف",
  "attendance.adjusted": "تم تعديل حضور",
  "attendance.shift_assigned": "تم تعيين وردية",
  "attendance.reconciled": "تم تسوية حضور",
  "attendance_policy.created": "تم إنشاء سياسة حضور",
  "attendance_policy.updated": "تم تحديث سياسة حضور",
  "attendance_shift.created": "تم إنشاء وردية",
  "attendance_shift.updated": "تم تحديث وردية",
  "leave_type.created": "تم إنشاء نوع إجازة",
  "leave_type.updated": "تم تحديث نوع إجازة",
  "leave_request.submitted": "تم تقديم طلب إجازة",
  "leave_request.manager_approved": "اعتمد المدير طلب إجازة",
  "leave_request.approved": "تم اعتماد طلب إجازة",
  "leave_request.rejected": "رُفض طلب إجازة",
  "leave_request.cancelled": "أُلغي طلب إجازة",
  "document.uploaded": "تم رفع مستند",
  "document.downloaded": "تم تنزيل مستند",
  "document.registered": "تم تسجيل مستند",
  "document.revised": "تم إصدار مراجعة مستند",
  "document.submitted": "تم تقديم مستند",
  "document.approved": "تم اعتماد مستند",
  "document.rejected": "رُفض مستند",
  "document.resubmit_required": "مطلوب إعادة تقديم مستند",
  "document.archived": "أرشفة المستند",
  "document.restored": "استعادة المستند",
  "document_intelligence.extracted": "تم استخراج بيانات المستند",
  "document_intelligence.failed": "فشل تحليل المستند",
  "document_intelligence.verified": "تم التحقق من المستند",
  "project.created": "تم إنشاء مشروع",
  "project.updated": "تم تحديث مشروع",
  "project.archived": "تم أرشفة مشروع",
  "workflow.started": "بدأ مسار العمل",
  "workflow.step.completed": "اكتملت خطوة مسار العمل",
  "workflow.mobilization.readiness_changed": "تم تحديث جاهزية التجهيز",
  "workflow.step.deadline_changed": "تم تحديث موعد المرحلة",
  "workflow.step.deadline_warning": "اقترب موعد انتهاء المرحلة",
  "workflow.step.overdue": "تأخرت مرحلة مسار العمل",
  "workflow.completed": "اكتمل مسار العمل",
  "workflow.cancelled": "أُلغي مسار العمل",
  "project.stage.started": "بدأت مرحلة مشروع",
  "project.stage.completed": "اكتملت مرحلة مشروع",
  "project.member.assigned": "تم تعيين عضو للمشروع",
  "project.health_changed": "تغيرت حالة صحة المشروع",
  "approval.created": "أُنشئ طلب اعتماد",
  "workflow.approval.requested": "أُرسلت المرحلة للاعتماد",
  "approval.document.linked": "رُبط مستند داعم بالاعتماد",
  "approval.overdue": "طلب اعتماد متأخر",
  "approval.approved": "تم اعتماد الطلب",
  "approval.rejected": "رُفض طلب الاعتماد",
  "approval.resubmitted": "أُعيد تقديم طلب اعتماد",
  "contract.created": "تم إنشاء عقد",
  "supplier.created": "تم إنشاء مورّد",
  "purchase_request.created": "تم إنشاء طلب شراء",
  "purchase_request.submitted": "تم تقديم طلب شراء",
  "purchase_request.approved": "تم اعتماد طلب شراء",
  "purchase_request.rejected": "رُفض طلب شراء",
  "rfq.issued": "تم إصدار طلب عرض سعر",
  "quotation.recommended": "تم ترشيح عرض سعر",
  "purchase_order.approved": "تم اعتماد أمر شراء",
  "purchase_order.issued": "تم إصدار أمر شراء",
  "notification.preference.changed": "تم تحديث تفضيلات التنبيه",
  "organization.management_notification_email.changed": "تم تحديث بريد تنبيهات الإدارة",
  "organization.management_notification_whatsapp.changed": "تم تحديث واتساب تنبيهات الإدارة",
  "profile.phone.changed": "تم تحديث رقم الجوال",
  "profile.whatsapp_opt_in.changed": "تم تحديث موافقة واتساب التشغيلية",
  "push.subscription.created": "تم تفعيل إشعارات الجهاز",
  "push.subscription.revoked": "أُلغي اشتراك الإشعارات",
};

const ENTITY_LABELS: Record<string, string> = {
  employee: "موظف",
  workplace: "موقع عمل",
  attendance: "حضور",
  document: "مستند",
  document_intelligence: "ذكاء المستندات",
  project: "مشروع",
  project_stage: "مرحلة مشروع",
  approval: "اعتماد",
  approval_request: "طلب اعتماد",
  workflow_instance: "مسار عمل",
  workflow_instance_step: "خطوة مسار عمل",
  role: "دور",
  leave_request: "إجازة",
  notification: "تنبيه",
};

export function auditActionLabel(action: string): string {
  return ACTION_LABELS[action] ?? action;
}

export function auditEntityLabel(entityType: string): string {
  return ENTITY_LABELS[entityType] ?? entityType;
}
